'use client';

import Image from 'next/image';
import Link from 'next/link';
import { useLanguage } from '../lib/i18n';
import BrandMark from '../components/BrandMark';

/**
 * /card — the digital business card of the Grimaldi Network.
 *
 * One screen, shareable as a single URL: headshot, name, role, direct
 * channels, the three domains, a downloadable vCard and a QR that always
 * points back here. Rendered in the visitor's locale like every other
 * surface of the site.
 */

const LINKS = {
  email: 'vincenzo@igrimaldi.engineering',
  github: 'https://github.com/iceccarelli',
  linkedin: 'https://www.linkedin.com/in/vincenzo-ceccarelli-grimaldi-2912b42a0',
  x: 'https://x.com/Vince87Grimaldi',
  instagram: 'https://www.instagram.com/grimaldiengineering/',
};

export default function CardPage() {
  const { t } = useLanguage();

  return (
    <main className="bizcard-stage">
      <article className="bizcard">
        {/* Identity */}
        <header className="bizcard-header">
          <div className="bizcard-portrait">
            <Image
              src="/vincenzo_grimaldi_headshot.jpg"
              alt="Vincenzo Grimaldi"
              width={132}
              height={132}
              priority
            />
          </div>
          <span className="section-kicker">{t.card.kicker}</span>
          <h1>Vincenzo Grimaldi</h1>
          <p className="bizcard-role">{t.card.role}</p>
          <p className="bizcard-tagline">{t.card.tagline}</p>
          <p className="bizcard-availability">
            <span className="live-dot" /> {t.card.availability}
          </p>
        </header>

        {/* Channels */}
        <div className="bizcard-rows">
          <a className="bizcard-row" href={`mailto:${LINKS.email}`}>
            <span className="bizcard-row-label">{t.card.email}</span>
            <span className="bizcard-row-value">{LINKS.email}</span>
          </a>
          <Link className="bizcard-row" href="/">
            <span className="bizcard-row-label">{t.card.website}</span>
            <span className="bizcard-row-value">igrimaldi.engineering</span>
          </Link>
          <a className="bizcard-row" href={LINKS.github} target="_blank" rel="noopener noreferrer">
            <span className="bizcard-row-label">{t.card.githubLabel}</span>
            <span className="bizcard-row-value">github.com/iceccarelli</span>
          </a>
          <a className="bizcard-row" href={LINKS.linkedin} target="_blank" rel="noopener noreferrer">
            <span className="bizcard-row-label">LinkedIn</span>
            <span className="bizcard-row-value">Vincenzo Ceccarelli Grimaldi</span>
          </a>
        </div>

        {/* The three domains */}
        <div className="bizcard-network">
          <span className="bizcard-row-label">{t.card.networkLabel}</span>
          <div className="bizcard-domains">
            <Link href="/">igrimaldi.engineering</Link>
            <a href="https://engineeringgrimaldi.com" target="_blank" rel="noopener noreferrer">
              engineeringgrimaldi.com
            </a>
            <a href="https://grimaldi.ca" target="_blank" rel="noopener noreferrer">
              grimaldi.ca
            </a>
          </div>
        </div>

        {/* Actions + QR */}
        <div className="bizcard-actions">
          <div className="bizcard-buttons">
            <a className="primary-button" href="/card.vcf" download>
              {t.card.saveContact}
            </a>
            <a className="secondary-button" href={`mailto:${LINKS.email}`}>
              {t.card.connect}
            </a>
          </div>
          <figure className="bizcard-qr">
            {/* Generated by the site from its own origin — survives redesigns
                and domain changes without a stale printed code. */}
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src="/card/qr" alt="QR code for this business card" width={112} height={112} />
            <figcaption>{t.card.scanToShare}</figcaption>
          </figure>
        </div>

        <footer className="bizcard-foot">
          <div style={{ display: 'flex', justifyContent: 'center', marginBottom: '0.85rem' }}>
            <BrandMark size={34} />
          </div>
          <Link href="/">{t.card.backHome}</Link>
        </footer>
      </article>
    </main>
  );
}
